### ISSUE TITLE
Usage of table=T and ci=T in svyjskm

### ISSUE THREAD

**Issue by st-weiss** [jinseob2kim/jskm#1]
Hi,

I want to warmly thank you for your contribution and would like to ask you how risk tables and confidence intervals can be plotted. Any help would be appreciated, an extensive example would be valuable.

Best Wishes

**Comment by jinseob2kim** [comment]
Thanks for good feedback. 

1. I add ci option to svyjskm. (version 0.2.4)
 - If you get svykm object with se = T option, you can get plot with ci. (see README)

2. Unfortunately, I don't know how to get the risk table easy. If you know, please answer me. 

Thanks.
