### ISSUE TITLE
The weighted survival curve drawn by the jskm package is different from the survival curve obtained by weighting the surfit function. Why?

### ISSUE THREAD

**Issue by zhangkaicr** [jinseob2kim/jskm#10]
library(survival)
library(jskm)
library(survminer)
library(survey)
library(WeightIt)

#Load dataset
data("cancer")
df <- na.omit(colon)

#Constructing grouping variables
df$rx <- ifelse(df$rx=="Obs",0,1)

#alculating the weight of the confounding factors.
weight <- weightit(rx~differ+etype+nodes,data=df)

#Draw IPTW-KM using the survminer package
fit <- survfit(Surv(time,status)~rx, weights = weight$weights,data=df)
ggsurvplot(fit,data = colon,pval = T,risk.table = T)
![image](https://github.com/jinseob2kim/jskm/assets/74847937/e5dfff82-7820-431b-b997-fbf54f1ac00e)

# Draw weighted KM using the JSkm package
dfsvy<-svydesign(id=~1, weights = weight$weights, data=df)
s2 <-svykm(Surv(time,status) ~ rx, design = dfsvy)
svyjskm(s2,pval = T,table = T)
![image](https://github.com/jinseob2kim/jskm/assets/74847937/32d8a82b-1575-431b-b222-358ec4f2d067)

#table function to view the grouping ratio
table(df$rx)

As seen from the demo code and chart above, the number of patients in the risk table of the jskm package is the same as the original number, but the one obtained by using the weighted survfit function is not the same. In addition, the P values ​​calculated by the two methods are also different. I don't know why this happens, hope to get your answer, thank you very much

**Comment by jinseob2kim** [comment]
Hello zhangkaicr. 
I checked and the survival estimates are the same for both methods.
It seems that the ggsurvplot function does not consider the weights option of the survifit function.

**Comment by zhangkaicr** [comment]
Thank you for your answer. Can you share the code for checking the two methods so that I can learn from it? Thank you very much.

**Comment by jinseob2kim** [comment]
I compare 2 survival estimate using 

```r
## weight
summary(fit)

## svy
data.frame(time =s2[[1]]$time, surv = s2[[1]]$surv)
data.frame(time =s2[[2]]$time, surv = s2[[2]]$surv)

```

**Comment by zhangkaicr** [comment]
thank you for your reply

**Comment by Ink-Mo** [comment]
@jinseob2kim, I have I encountered the same problem.

The pvalue I obtained from two functions are different. Then, I checked this by SAS software.

When I add argument of weights in SAS, the results of pvalue are same to obtained from:
 fit <- survfit(Surv(time,status)~rx, weights = weight$weights,data=df) 
 ggsurvplot(fit,data = colon,pval = T)

When I drop argument of weights in SAS, the results of pvalue are similar to it from:
 fit <- survfit(Surv(time,status)~rx, data=df) 
  ggsurvplot(fit,data = colon,pval = T)

What went wrong?  Is the pvalue from `svykm ` wrong?

**Comment by jinseob2kim** [comment]
As I know, `ggsurvplot` uses `survival::survdiff` to calculate log-rank p. But `survdiff` can't use IPTW weights. See line 206 in https://github.com/kassambara/survminer/blob/master/R/surv_pvalue.R

'svyjskm` uses `survey::svyranktest`

**Comment by Ink-Mo** [comment]
> As I know, `ggsurvplot` uses `survival::survdiff` to calculate log-rank p. But `survdiff` can't use IPTW weights. See line 206 in https://github.com/kassambara/survminer/blob/master/R/surv_pvalue.R
> 
> 'svyjskm`uses`survey::svyranktest`


@jinseob2kim , Oh, Sorry~. I got it mixed up.
When I applied `survfit ` fitting with `weights`, then, the `ggsurvplot ` could not get the pvalue. I used `IPWsurvival::adjusted.LR` to abtain the pvalue which is equal to the pvalue from SAS. I just used  `ggsurvplot `  to plot the survival curve.

However, the pvalue from `survey::svyranktest` are different  from the one obtained from SAS.
My results are following:

p2 <- adjusted.LR(df$time, df$Status, df$group, weights = df$weights);p2
$statistic
[1] -2.974184

$p.value
[1] 0.002937693

In SAS:
<img width="716" alt="截屏2024-07-08 12 54 54" src="https://github.com/jinseob2kim/jskm/assets/46460652/5b75116b-46b2-445f-9e0b-5528cf00915d">

You can reference: https://documentation.sas.com/doc/en/statug/15.2/statug_lifetest_syntax08.htm
<img width="927" alt="截屏2024-07-08 12 59 24" src="https://github.com/jinseob2kim/jskm/assets/46460652/e70d2c71-7fd0-441a-9d82-c63ea5170e4a">


However, in `survey::svyranktest`
svylogrank(Surv(time, Status) ~ group , design = dataIPTW)
[[1]]
         score                               
[1,] -18.17397 5.682577 -3.198192 0.001382921


[[2]]
       Chisq            p 
10.228433148  0.001382921 

attr(,"class")
[1] "svylogrank"



I do not know how `survey::svyranktest` computes the p-value, but I think the SAS result is correct.

**Comment by jinseob2kim** [comment]
`survey::svyranktest` use `Lumley, T., & Scott, A. J. (2013). Two-sample rank tests under complex sampling. BIOMETRIKA, 100 (4), 831-842.` (https://www.jstor.org/stable/43305573)
