### ISSUE TITLE
How to calculate the hazard ratio through the cox regression analysis?

### ISSUE THREAD

**Issue by zjsty** [jinseob2kim/jskm#12]
How to calculate the hazard ratio through the cox regression analysis? Especially for the first part of landmark survival? Thank You!

**Comment by zjsty** [comment]
How to calculate the hazard ratio through the cox regression analysis? Especially for the first part of landmark survival? Thank You! @jinseob2kim

**Comment by jinseob2kim** [comment]
@zjsty Please see https://github.com/jinseob2kim/jskm/issues/6#issuecomment-1639389374
