### ISSUE TITLE
How to cite your work of 'jskm' in the article?

### ISSUE THREAD

**Issue by zjsty** [jinseob2kim/jskm#13]
How to cite your work of 'jskm' in the article? @jinseob2kim

**Comment by jinseob2kim** [comment]
please use `citation("jskm")` 
<img width="558" alt="image" src="https://github.com/jinseob2kim/jskm/assets/33089958/9cdcd43f-e765-48e8-b610-74cb324a4a77">

Or please see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10307816/
