### ISSUE TITLE
risktable

### ISSUE THREAD

**Issue by aghaynes** [jinseob2kim/jskm#3]
Hi! 
Nice function! 

Is it possible to align the risk table so that the numbers are in line with the marks on the graph? It would look much better like that...

![grafik](https://user-images.githubusercontent.com/6594028/96581987-f2c37b80-12da-11eb-9b65-b5aa3badbe3d.png)

Thanks!

**Comment by jinseob2kim** [comment]
Thanks for feedback.

I have not completely solved this problem. (only some improvement)

Please run with jskm 0.4.1.
