### ISSUE TITLE
cannot use "cut.landmark" with my own database

### ISSUE THREAD

**Issue by xiaohedegithub** [jinseob2kim/jskm#4]
Sorry to bother, here is my problem.
I can run the code "jskm(fit1)", but cannot run "jskm(fit1, cut.landmark = 500)" when I use my own data. It display "Error in form[[2]][[2]] : object of type 'symbol' is not subsettable".
But I can run "jskm(fit1, cut.landmark = 500)" with the example database "colon".
I've searched in the internet a lot but still cannot solve this problem.
I will be so appreciated if someone can help.

**Comment by xiaohedegithub** [comment]
Sure. It means a lot to me if the problem can be solved.

MyCode:

mydf <- read.csv("1.csv", header = TRUE)
survobj <- Surv(mydf$time,mydf$status)
fit <- survfit(survobj ~ diabetes, data = mydf)
jskm(fit,
     mark =F,pval =T,table = T,label.nrisk = "No. at risk",
     #ci = T, 
     cumhaz = T, 
     cut.landmark = 4,
     size.label.nrisk = 8,
     xlabs = "time", 
     ylabs = "", 
     ystrataname = "",
     ystratalabs = c("", ""),
     legendposition=c(0.6,0.3),
     timeby =24, 
     ylims = c(0, 1))



Here is my data:
[1.csv](https://github.com/jinseob2kim/jskm/files/11035999/1.csv)

If you need other information, please let me know.
Thanks again!!!!

**Comment by jinseob2kim** [comment]
Please try the below
`fit <- survfit(Surv(time, status)~ diabetes, data = mydf)`

Currently, jskm only support the above formula

**Comment by xiaohedegithub** [comment]
Thank you for your answer!
I tried as you command, but it still went wrong, the error display as "Error in .subset2(x, i, exact = exact) : no such index at level 1".
If I deleted "cut.landmark = 4", the code can draw a plot; but it went error with this line present.

Again so sorry to bother you, I will be very appreacited if you can help me with it.
Thank you!!!

**Comment by xiaohedegithub** [comment]
Thank you for your answer!
I tried as you command, but it still went wrong, the error display as "Error in .subset2(x, i, exact = exact) : no such index at level 1".
If I deleted "cut.landmark = 4", the code can draw a plot; but it went error with this line present.

Again so sorry to bother you, I will be very appreacited if you can help me with it.
Thank you!!!

**Comment by xiaohedegithub** [comment]
Thank you for your answer!
I tried as you command, but it still went wrong, the error display as "Error in .subset2(x, i, exact = exact) : no such index at level 1".
If I deleted "cut.landmark = 4", the code can draw a plot; but it went error with this line present.

Again so sorry to bother you, I will be very appreacited if you can help me with it.
Thank you!!!

**Comment by jinseob2kim** [comment]
I think "cut.landmark =4" is to short. How about cut.landmark = 20?
* your 1.csv file only have diabetes "2", please show me more lines
