### ISSUE TITLE
How are standard errors calculated in a weighted sample

### ISSUE THREAD

**Issue by PStaus** [jinseob2kim/jskm#5]
Thank you for the great functions. Plotting weighted cumulative incidences is easy now.
I wonder if and how weights are taken into account when calculating standard errors in the weighted sample. Could you give some more explanation on that? svykm( se = T, design = weighted_design)
Thanks a lot in advance

**Comment by jinseob2kim** [comment]
I'm glad to help you. Could you see `km.stderr` function in https://github.com/cran/survey/blob/master/R/svykm.R ?
