### ISSUE TITLE
How to explain the P value in the Landmark analysis :)

### ISSUE THREAD

**Issue by DaruiGao** [jinseob2kim/jskm#6]
Sorry to bother.

I choose a landmark point as 10 in my procject and two P values were shown in the figure with 0.029 and 0.168, respectively.  I would like to ask you about the meaning of these two P values and could we calculate HR value with this package?

Thanks in advance :) .

**Comment by jinseob2kim** [comment]
pvalue1: Logrank test with data before cut.landmark
pvalue2: same after cut.landmark

I'm sorry, HR can't be calculated with jskm package.

**Comment by jinseob2kim** [comment]
> pvalue1: Logrank test with data before cut.landmark pvalue2: same after cut.landmark
> 
> I'm sorry, HR can't be calculated with jskm package.

You can get HR with the code below

```r
data1 <- colon
var.event <- "status"
var.time <- "time"
cut.landmark <- 365
data1[[var.event]][data1[[var.time]] >= cut.landmark] <- 0
data1[[var.time]][data1[[var.time]] >= cut.landmark] <- cut.landmark

# before landmark
hr1 <- coxph(Surv(time, status) ~ sex, data1)
# after landmark
hr2 <- coxph(Surv(time, status) ~ sex, colon[colon[[var.time]] >= cut.landmark, ])
```
